/*
 Navicat Premium Data Transfer

 Source Server         : SITB DEV, PREDEV 2025
 Source Server Type    : MySQL
 Source Server Version : 100608
 Source Host           : localhost:3306
 Source Schema         : sitb2025predev

 Target Server Type    : MySQL
 Target Server Version : 100608
 File Encoding         : 65001

 Date: 10/11/2025 16:16:34
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for lap_tbc_03so_ckg
-- ----------------------------
DROP TABLE IF EXISTS `lap_tbc_03so_ckg`;
CREATE TABLE `lap_tbc_03so_ckg`  (
  `register_id` bigint UNSIGNED NOT NULL,
  `id_reg_terduga` bigint UNSIGNED NULL DEFAULT NULL,
  `tahun` int NULL DEFAULT NULL,
  `bulan_id` int NULL DEFAULT NULL,
  `bulan` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_daftar` date NULL DEFAULT NULL,
  `fasyankes_provinsi_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `fasyankes_provinsi_kode` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fasyankes_provinsi_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fasyankes_kabupaten_id` int UNSIGNED NULL DEFAULT NULL,
  `fasyankes_kabupaten_kode` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fasyankes_kabupaten_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fasyankes_kecamatan_id` int UNSIGNED NULL DEFAULT NULL,
  `fasyankes_kecamatan_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `jenis_fasyankes_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `jenis_fasyankes_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `jenis_pemilik_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `jenis_pemilik_fasyankes_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_pemilik_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `status_pemilik_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fasyankes_id` int UNSIGNED NULL DEFAULT NULL,
  `fasyankes_kode` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fasyankes_nama` varchar(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `no_reg_fasyankes` int UNSIGNED NULL DEFAULT NULL,
  `no_reg_tbc_kab_kota` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_pengisian_data` date NULL DEFAULT NULL,
  `no_rekam_medis` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `no_bpjs` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_pengobatan_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `status_pengobatan` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `person_id` bigint UNSIGNED NULL DEFAULT NULL,
  `nama_pasien` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `nik` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kelompok_umur_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `kategori_umur_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `umur` tinyint UNSIGNED NULL DEFAULT NULL,
  `umur_bl` tinyint UNSIGNED NULL DEFAULT NULL,
  `jenis_kelamin_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `jenis_kelamin` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pekerjaan_id` int UNSIGNED NULL DEFAULT NULL,
  `pekerjaan_id_text` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_hamil_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `status_hamil` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_provinsi_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `pasien_provinsi_kode` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_provinsi_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_kabupaten_id` int UNSIGNED NULL DEFAULT NULL,
  `pasien_kabupaten_kode` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_kabupaten_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_kecamatan_id` int UNSIGNED NULL DEFAULT NULL,
  `pasien_kecamatan_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_kelurahan_id` int UNSIGNED NULL DEFAULT NULL,
  `pasien_kelurahan_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_alamat` varchar(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `dilakukan_pemeriksaan_kontak_id` tinyint(1) UNSIGNED NULL DEFAULT 0,
  `dilakukan_pemeriksaan_kontak` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `asal_rujukan_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `fasyankes_rujukan_id` int UNSIGNED NULL DEFAULT NULL,
  `organisasi_rujukan_id` int UNSIGNED NULL DEFAULT NULL,
  `asal_rujukan_lain` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `dirujuk_dikirim_oleh` varchar(353) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tipe_diagnosis_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `tipe_diagnosis_tbc` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lokasi_penyakit_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `lokasi_penyakit_nama` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tipe_pasien_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tipe_pasien_nama` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_hiv_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `status_hiv_nama` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `skoring_tbc_anak` tinyint UNSIGNED NULL DEFAULT NULL,
  `tgl_mulai_pengobatan` date NULL DEFAULT NULL,
  `paduan_oat_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `paduan_oat` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `sumber_obat_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `sumber_obat` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `paduan_pengobatan_id` int UNSIGNED NULL DEFAULT NULL,
  `paduan_pengobatan` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hasil_mik1` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hasil_mik2` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_hasil_mik` date NULL DEFAULT NULL,
  `hasil_mik` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_hasil_xpert` date NULL DEFAULT NULL,
  `hasil_xpert_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `hasil_xpert` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT 'hasil akhir',
  `bdmax_tgl_hasil` date NULL DEFAULT NULL,
  `bdmax_hasil_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `bdmax_hasil` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hasil_tcm_digunakan` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hasil_tcm_tgl` date NULL DEFAULT NULL,
  `hasil_tcm_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `hasil_tcm` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hasil_biakan` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_lpa` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_mtb` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_rif` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_inh` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_inhh` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_eto` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_pto` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `no_reg_lab_akhir_bulan_2` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `mikroskopis_akhir_bulan_2` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `no_reg_lab_akhir_bulan_3` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `mikroskopis_akhir_bulan_3` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `no_reg_lab_bulan_5` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `mikroskopis_bulan_5` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `no_reg_lab_akhir_pengobatan` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `mikroskopis_akhir_pengobatan` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_akhir_pengobatan` date NULL DEFAULT NULL,
  `hasil_pengobatan_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `hasil_akhir_pengobatan` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_dianjurkan_tes_hiv` date NULL DEFAULT NULL,
  `tgl_tes_hiv` date NULL DEFAULT NULL,
  `hasil_hiv_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `hasil_tes_hiv` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `layanan_pdp_ppk_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `layanan_pdp_ppk` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `layanan_pdp_art_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `layanan_pdp_art` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `status_dm_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `hasil_test_dm_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `kegiatan_tbc_dm` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `terapi_dm_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `kegiatan_tbc_terapi_dm` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pindah_pasien_ro_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `dipindah_ke_tbc_ro` varchar(2) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `keterangan` varchar(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_hapus_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `update_at` datetime NOT NULL,
  PRIMARY KEY (`register_id`) USING BTREE,
  INDEX `idx_lap_tbc_03so_update`(`update_at`) USING BTREE,
  INDEX `idx_lap_tbc_03so_sum`(`kelompok_umur_id`, `jenis_kelamin_id`, `tipe_diagnosis_id`, `lokasi_penyakit_id`, `tipe_pasien_id`, `fasyankes_id`) USING BTREE,
  INDEX `idx_lap_tbc_03so_00`(`fasyankes_id`) USING BTREE,
  INDEX `idx_lap_tbc_03so_01`(`id_reg_terduga`) USING BTREE,
  INDEX `idx_lap_tbc_03so_02`(`status_hapus_id`, `fasyankes_id`, `tgl_mulai_pengobatan`) USING BTREE,
  INDEX `idx_lap_tbc_03so_03`(`status_hapus_id`, `tgl_mulai_pengobatan`) USING BTREE,
  INDEX `idx_lap_tbc_03so_04`(`status_hapus_id`, `status_pengobatan_id`, `tgl_mulai_pengobatan`) USING BTREE,
  INDEX `idx_lap_tbc_03so_05`(`person_id`) USING BTREE,
  INDEX `idx_lap_tbc_03so_06`(`status_hapus_id`, `tgl_mulai_pengobatan`, `lokasi_penyakit_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
