/*
 Navicat Premium Data Transfer

 Source Server         : SITB DEV, PREDEV 2025
 Source Server Type    : MySQL
 Source Server Version : 100608
 Source Host           : localhost:3306
 Source Schema         : sitb2025predev

 Target Server Type    : MySQL
 Target Server Version : 100608
 File Encoding         : 65001

 Date: 10/11/2025 16:16:54
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for lap_tbc_03ro
-- ----------------------------
DROP TABLE IF EXISTS `lap_tbc_03ro`;
CREATE TABLE `lap_tbc_03ro`  (
  `register_id` bigint UNSIGNED NOT NULL,
  `id_reg_terduga` bigint UNSIGNED NULL DEFAULT NULL,
  `tahun` int NULL DEFAULT NULL,
  `bulan_id` int NULL DEFAULT NULL,
  `bulan` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_mulai_pengobatan` date NULL DEFAULT NULL,
  `fasyankes_provinsi_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `fasyankes_provinsi_kode` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fasyankes_provinsi_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fasyankes_kabupaten_id` int UNSIGNED NULL DEFAULT NULL,
  `fasyankes_kabupaten_kode` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fasyankes_kabupaten_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kecamatan_id` int UNSIGNED NULL DEFAULT NULL,
  `fasyankes_kecamatan_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `jenis_fasyankes_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `jenis_fasyankes_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `jenis_pemilik_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `jenis_pemilik_fasyankes_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_pemilik_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `status_pemilik_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fasyankes_id` int UNSIGNED NULL DEFAULT NULL,
  `fasyankes_kode` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fasyankes_nama` varchar(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `no_reg_fasyankes` int UNSIGNED NULL DEFAULT NULL,
  `no_reg_kab` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_pengisian_data` date NULL DEFAULT NULL,
  `no_rekam_medis` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `person_id` bigint UNSIGNED NULL DEFAULT NULL,
  `nik` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `no_bpjs` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `nama_pasien` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `umur` tinyint UNSIGNED NULL DEFAULT NULL,
  `kelompok_umur_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `kategori_umur_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `jenis_kelamin_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `jenis_kelamin` varchar(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `pekerjaan_id` int UNSIGNED NULL DEFAULT NULL,
  `pekerjaan` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_hamil_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `status_hamil` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_provinsi_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `pasien_provinsi_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_kabupaten_id` int UNSIGNED NULL DEFAULT NULL,
  `pasien_kabupaten_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_kecamatan_id` int UNSIGNED NULL DEFAULT NULL,
  `pasien_kecamatan_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_kelurahan_id` int UNSIGNED NULL DEFAULT NULL,
  `pasien_kelurahan_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pasien_alamat` varchar(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `dilakukan_pemeriksaan_kontak_id` tinyint(1) UNSIGNED NULL DEFAULT 0,
  `dilakukan_pemeriksaan_kontak` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT '',
  `asal_rujukan_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `fasyankes_rujukan_id` int UNSIGNED NULL DEFAULT NULL,
  `organisasi_rujukan_id` int UNSIGNED NULL DEFAULT NULL,
  `dirujuk_dikirim_oleh` varchar(353) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `nama_fasyankes_satelit_tbc_ro` varchar(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lokasi_penyakit_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `lokasi_penyakit_nama` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tipe_pasien_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tipe_pasien_nama` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `terduga_ro_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `riwayat_pengobatan_tbc` varchar(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_hiv_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `status_hiv_nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hasil_foto_toraks_kode` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hasil_foto_toraks` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `paduan_pengobatan_awal` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `paduan_pengobatan_akhir` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `paduan_oat_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `paduan_oat_nama` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `paduan_oat` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_pengambilan_dst` date NULL DEFAULT NULL,
  `tgl_hasil_dst` date NULL DEFAULT NULL,
  `tgl_hasil_xpert` date NULL DEFAULT NULL,
  `hasil_xpert_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `hasil_xpert` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT 'hasil akhir',
  `bdmax_tgl_hasil` date NULL DEFAULT NULL,
  `bdmax_hasil_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `bdmax_hasil` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hasil_tcm_digunakan` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hasil_tcm_tgl` date NULL DEFAULT NULL,
  `hasil_tcm_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `hasil_tcm` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `xdr_tgl_hasil` date NULL DEFAULT NULL,
  `xdr_hasil` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `xdr_hasil_mtb` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `xdr_hasil_h` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `xdr_hasil_ht` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `xdr_hasil_eto` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `xdr_hasil_fq` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `xdr_hasil_fqt` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `xdr_hasil_amk` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `xdr_hasil_km` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `xdr_hasil_cm` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_tgl_hasil` date NULL DEFAULT NULL,
  `lini1_hasil_lpa` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_mtb` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_rif` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_inh` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_inhh` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_eto` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini1_hasil_pto` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `lini2_tgl_hasil` date NULL DEFAULT NULL,
  `hasil_lpa` int NULL DEFAULT NULL,
  `hasil_mtb` int NULL DEFAULT NULL,
  `hasil_lfx` int NULL DEFAULT NULL,
  `hasil_mfx` int NULL DEFAULT NULL,
  `hasil_mfx_dt` int NULL DEFAULT NULL,
  `hasil_km` int NULL DEFAULT NULL,
  `hasil_amk` int NULL DEFAULT NULL,
  `hasil_cm` int NULL DEFAULT NULL,
  `kepekaan_ht` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_h` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_km` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_cm` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_lfx` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_mfxt` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_mfx` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_x1` varchar(12) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_x2` varchar(12) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_x3` varchar(12) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_x4` varchar(12) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_x5` varchar(12) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kepekaan_x6` varchar(12) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v1_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v1_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v2_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v2_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v3_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v3_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v4_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v4_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v4_bta_2` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v4_b_2` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v5_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v5_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v5_bta_2` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v5_b_2` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v6_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v6_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v6_bta_2` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v6_b_2` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v7_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v7_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v8_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v8_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v9_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v9_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v10_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v10_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v11_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v11_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v12_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v12_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v13_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v13_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v14_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v14_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v15_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v15_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v16_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v16_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v17_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v17_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v18_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v18_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v19_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v19_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v20_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v20_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v21_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v21_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v22_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v22_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v23_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v23_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v24_bta` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `v24_b` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_akhir_pengobatan` date NULL DEFAULT NULL,
  `hasil_pengobatan_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `hasil_akhir_pengobatan` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hasil_test_hiv_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `hasil_test_hiv` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kotrimoksasol` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hasil_art_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `hasil_art` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_dm_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `hasil_test_dm_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `hasil_test_dm` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `terapi_dm_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `hasil_terapi_dm` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan` varchar(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_hapus_id` tinyint(1) UNSIGNED NULL DEFAULT 0,
  `update_at` datetime NOT NULL,
  PRIMARY KEY (`register_id`) USING BTREE,
  INDEX `idx_lap_tbc_03ro_order`(`fasyankes_kabupaten_kode`, `fasyankes_nama`, `nama_pasien`) USING BTREE,
  INDEX `idx_lap_tbc_03ro_update`(`update_at`) USING BTREE,
  INDEX `idx_lap_tbc_03ro_01`(`id_reg_terduga`) USING BTREE,
  INDEX `idx_lap_tbc_03ro_02`(`status_hapus_id`, `fasyankes_id`, `tgl_mulai_pengobatan`, `paduan_oat_id`) USING BTREE,
  INDEX `idx_lap_tbc_03ro_03`(`status_hapus_id`, `tgl_mulai_pengobatan`, `paduan_oat_id`) USING BTREE,
  INDEX `idx_lap_tbc_03ro_04`(`fasyankes_id`) USING BTREE,
  INDEX `idx_lap_tbc_03ro_05`(`person_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
