/*
 Navicat Premium Data Transfer

 Source Server         : SITB DEV, PREDEV 2025
 Source Server Type    : MySQL
 Source Server Version : 100608
 Source Host           : localhost:3306
 Source Schema         : sitb2025predev

 Target Server Type    : MySQL
 Target Server Version : 100608
 File Encoding         : 65001

 Date: 07/11/2025 07:46:32
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for ta_skrining
-- ----------------------------
DROP TABLE IF EXISTS `ta_skrining`;
CREATE TABLE `ta_skrining`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `tgl_skrining` date NOT NULL,
  `kegiatan_id` smallint UNSIGNED NOT NULL,
  `kegiatan_lain` varchar(150) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `metode_id` tinyint NOT NULL,
  `tempat_skrining_id` tinyint UNSIGNED NOT NULL,
  `tempat_skrining_lain` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `jenis_unit_pelaksana_id` tinyint UNSIGNED NOT NULL,
  `unit_pelaksana_id` int UNSIGNED NULL DEFAULT NULL,
  `warga_negara_id` tinyint UNSIGNED NULL DEFAULT 1,
  `nama_peserta` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `alamat_ktp` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `provinsi_ktp_id` tinyint UNSIGNED NOT NULL,
  `kabupaten_ktp_id` int UNSIGNED NOT NULL,
  `kecamatan_ktp_id` int UNSIGNED NULL DEFAULT NULL,
  `kelurahan_ktp_id` int UNSIGNED NULL DEFAULT NULL,
  `status_domisili_id` tinyint UNSIGNED NOT NULL DEFAULT 1,
  `alamat_domisili` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `provinsi_domisili_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `kabupaten_domisili_id` int UNSIGNED NULL DEFAULT NULL,
  `kecamatan_domisili_id` int UNSIGNED NULL DEFAULT NULL,
  `kelurahan_domisili_id` int UNSIGNED NULL DEFAULT NULL,
  `nik` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `pekerjaan_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tgl_lahir` date NOT NULL,
  `umur_th` tinyint UNSIGNED NULL DEFAULT NULL,
  `umur_bl` tinyint UNSIGNED NULL DEFAULT NULL,
  `jenis_kelamin_id` tinyint UNSIGNED NOT NULL,
  `no_telp` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `berat_badan` float UNSIGNED NOT NULL,
  `tinggi_badan` float UNSIGNED NOT NULL,
  `imt` float UNSIGNED NULL DEFAULT NULL,
  `status_gizi_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `riwayat_kontak_tb_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `jenis_kontak_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `nama_kasus_indeks` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `nik_kasus_indeks` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `jenis_kasus_indeks_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_1_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_1_tgl` date NULL DEFAULT NULL,
  `risiko_2_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_3_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_4_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_5_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_6_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_7_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_8_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_9_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_10_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_10_tgl` date NULL DEFAULT NULL,
  `risiko_10_status_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `risiko_11_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_1_1_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_1_1_durasi` int NULL DEFAULT NULL,
  `gejala_1_2_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_1_3_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_1_4_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_1_5_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_2_1_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_2_1_durasi` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_2_2_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_2_3_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_2_4_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_2_5_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `gejala_6_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `hasil_skrining_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `cxr_pemeriksaan_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `cxr_alasan` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `cxr_tgl_periksa` date NULL DEFAULT NULL,
  `cxr_rujuk_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `cxr_jenis_rujuk_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `cxr_lab_internal_id` int UNSIGNED NULL DEFAULT NULL,
  `cxr_lab_eksternal_id` int UNSIGNED NULL DEFAULT NULL,
  `cxr_baca_ai_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `cxr_skor_ai` float UNSIGNED NULL DEFAULT NULL,
  `cxr_hasil_skor_ai_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `cxr_dilakukan_radiolog_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `cxr_pembacaan_radiolog` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `cxr_hasil_radiologi_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `cxr_simpulan_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `cxr_keterangan` varchar(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `terduga_tb_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tindak_lanjut_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tcm_pemeriksaan_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tcm_alasan` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `tcm_asal_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tcm_fasyankes_id` int UNSIGNED NULL DEFAULT NULL,
  `tcm_fasyankes` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tcm_tgl_kirim` date NULL DEFAULT NULL,
  `tcm_tgl_hasil` date NULL DEFAULT NULL,
  `tcm_hasil_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `diagnosis_tb_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `kasus_tb_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `pengobatan_mulai_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `pengobatan_alasan_tidak` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `tst_pemeriksaan_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tst_tgl_periksa` date NULL DEFAULT NULL,
  `tst_pembacaan_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tst_tgl_baca` date NULL DEFAULT NULL,
  `tst_alasan_tidak` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `tst_hasil_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tpt_eligible_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tpt_tindak_lanjut_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tpt_fasyankes_id` int UNSIGNED NULL DEFAULT NULL,
  `tpt_pemberian_id` tinyint UNSIGNED NULL DEFAULT NULL,
  `tpt_alasan_tidak` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `jenis_rujukan_id` tinyint(1) UNSIGNED NULL DEFAULT NULL,
  `dirujuk_ke_id` int UNSIGNED NULL DEFAULT NULL,
  `id_reg_terduga` bigint UNSIGNED NULL DEFAULT NULL,
  `tpt_id_reg` bigint UNSIGNED NULL DEFAULT NULL,
  `new_id` int UNSIGNED NULL DEFAULT NULL,
  `insert_by` int NULL DEFAULT NULL,
  `insert_at` datetime NULL DEFAULT NULL,
  `update_by` int NULL DEFAULT NULL,
  `update_at` datetime NULL DEFAULT NULL,
  `sumber_id` tinyint UNSIGNED NULL DEFAULT 1,
  `keterangan` varchar(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT '',
  `ckg_id` varchar(16) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `IX_ta_skrining_01`(`id_reg_terduga`) USING BTREE,
  INDEX `IX_ta_skrining_02`(`dirujuk_ke_id`) USING BTREE,
  INDEX `IX_ta_skrining_03`(`tpt_fasyankes_id`) USING BTREE,
  INDEX `IX_ta_skrining_04`(`cxr_jenis_rujuk_id`) USING BTREE,
  INDEX `IX_ta_skrining_05`(`nik`) USING BTREE,
  INDEX `IX_ta_skrining_06`(`unit_pelaksana_id`, `cxr_lab_internal_id`, `cxr_lab_eksternal_id`, `tgl_skrining`) USING BTREE,
  INDEX `IX_ta_skrining_07`(`tpt_id_reg`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4046680 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
